# Generated by Django 3.2.9 on 2022-02-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
